"""add sportsbook to parlays

Revision ID: 0dc324f654ef
Revises: 0001
Create Date: 2026-02-23 07:58:42.484410
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dc324f654ef'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint('app_settings_key_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('boxscores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_ot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_ot', sa.Integer(), nullable=True))
        batch_op.alter_column('raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint('boxscores_game_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_boxscores_game_id'), ['game_id'], unique=True)
        batch_op.drop_column('q4_away')
        batch_op.drop_column('q1_home')
        batch_op.drop_column('q2_away')
        batch_op.drop_column('q1_away')
        batch_op.drop_column('ot_home')
        batch_op.drop_column('q3_home')
        batch_op.drop_column('q3_away')
        batch_op.drop_column('q4_home')
        batch_op.drop_column('q2_home')
        batch_op.drop_column('ot_away')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('coaches_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_coaches_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_coaches_team_id'), ['team_id'], unique=False)
        batch_op.drop_constraint('coaches_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('depth_charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_depth_charts_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_charts_team_id'), ['team_id'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('parsed_status',
               existing_type=postgresql.ENUM('pending', 'success', 'partial', 'failed', name='parsestatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::parsestatus"))
        batch_op.alter_column('parsed_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('parser_used',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_documents_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_upload_date'), ['upload_date'], unique=False)

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_pick', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('player_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('drafts_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_drafts_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_drafts_year'), ['year'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('season_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('broadcast',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('games_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_games_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_status'), ['status'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injury_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('season_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('practice_status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint('injuries_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('headline',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint('news_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_news_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_team_id'), ['team_id'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('over_juice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('under_juice', sa.Integer(), nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('market_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('ou_juice_under')
        batch_op.drop_column('ou_juice_over')

    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odds_id', sa.Integer(), nullable=False))
        batch_op.alter_column('odds_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_odds_history_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_history_odds_id'), ['odds_id'], unique=False)
        batch_op.create_foreign_key(None, 'odds', ['odds_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('parlay_legs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('pick',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('parlays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sportsbook', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('stat_category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('stat_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('uq_player_stats', type_='unique')
        batch_op.create_unique_constraint('uq_player_stat', ['player_id', 'game_id', 'stat_category', 'stat_type'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('players_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_players_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('down', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_scoring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('score_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('clock',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('play_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('home_score')
        batch_op.drop_column('away_score')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('scoreboards', schema=None) as batch_op:
        batch_op.alter_column('time_remaining',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_scoreboards_game_id'), ['game_id'], unique=True)

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('season_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('seasons_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_seasons_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_seasons_year'), ['year'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('running', 'success', 'partial', 'failed', name='syncstatus'),
               nullable=False,
               existing_server_default=sa.text("'running'::syncstatus"))
        batch_op.alter_column('triggered_by',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
        batch_op.drop_index('ix_sync_logs_started_at')

    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('stat_category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('stat_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('uq_team_stats', type_='unique')
        batch_op.create_index(batch_op.f('ix_team_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_unique_constraint('uq_team_stat', ['team_id', 'game_id', 'stat_category', 'stat_type'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('conference',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('teams_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_teams_abbreviation'), ['abbreviation'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_api_id'), ['api_id'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('roof_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('surface',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('api_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('venues_api_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_venues_api_id'), ['api_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_venues_team_id'), ['team_id'], unique=False)
        batch_op.drop_constraint('venues_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('venues_team_id_fkey', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_venues_team_id'))
        batch_op.drop_index(batch_op.f('ix_venues_api_id'))
        batch_op.create_unique_constraint('venues_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('surface',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('roof_type')
        batch_op.drop_column('country')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_teams_api_id'))
        batch_op.drop_index(batch_op.f('ix_teams_abbreviation'))
        batch_op.create_unique_constraint('teams_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('division',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('conference',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_team_stat', type_='unique')
        batch_op.drop_index(batch_op.f('ix_team_stats_game_id'))
        batch_op.create_unique_constraint('uq_team_stats', ['team_id', 'game_id', 'stat_category', 'stat_type'])
        batch_op.alter_column('stat_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('stat_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('week')
        batch_op.drop_column('season_year')

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_logs_started_at', ['started_at'], unique=False)
        batch_op.alter_column('triggered_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('running', 'success', 'partial', 'failed', name='syncstatus'),
               nullable=True,
               existing_server_default=sa.text("'running'::syncstatus"))
        batch_op.alter_column('errors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_seasons_year'))
        batch_op.drop_index(batch_op.f('ix_seasons_api_id'))
        batch_op.create_unique_constraint('seasons_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('season_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('scoreboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoreboards_game_id'))
        batch_op.alter_column('raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('time_remaining',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('play_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('clock',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('score_type')
        batch_op.drop_column('is_scoring')
        batch_op.drop_column('distance')
        batch_op.drop_column('down')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_api_id'))
        batch_op.create_unique_constraint('players_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_player_stat', type_='unique')
        batch_op.create_unique_constraint('uq_player_stats', ['player_id', 'game_id', 'stat_category', 'stat_type'])
        batch_op.alter_column('stat_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('stat_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('week')
        batch_op.drop_column('season_year')

    with op.batch_alter_table('parlays', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('sportsbook')

    with op.batch_alter_table('parlay_legs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.alter_column('pick',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_odds_history_odds_id'))
        batch_op.drop_index(batch_op.f('ix_odds_history_game_id'))
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('odds_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('odds_id')

    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ou_juice_over', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ou_juice_under', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('market_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('under_juice')
        batch_op.drop_column('over_juice')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_news_team_id'))
        batch_op.drop_index(batch_op.f('ix_news_player_id'))
        batch_op.drop_index(batch_op.f('ix_news_api_id'))
        batch_op.create_unique_constraint('news_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('injuries_team_id_fkey', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('practice_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('season_year')
        batch_op.drop_column('week')
        batch_op.drop_column('injury_type')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_games_status'))
        batch_op.drop_index(batch_op.f('ix_games_season_id'))
        batch_op.drop_index(batch_op.f('ix_games_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_games_away_team_id'))
        batch_op.drop_index(batch_op.f('ix_games_api_id'))
        batch_op.create_unique_constraint('games_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('broadcast',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('season_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_drafts_year'))
        batch_op.drop_index(batch_op.f('ix_drafts_api_id'))
        batch_op.create_unique_constraint('drafts_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('player_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('overall_pick')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_upload_date'))
        batch_op.drop_index(batch_op.f('ix_documents_file_type'))
        batch_op.alter_column('parser_used',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('parsed_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('parsed_status',
               existing_type=postgresql.ENUM('pending', 'success', 'partial', 'failed', name='parsestatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::parsestatus"))
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('parsed_at')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('depth_charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_depth_charts_team_id'))
        batch_op.drop_index(batch_op.f('ix_depth_charts_player_id'))
        batch_op.alter_column('unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('coaches_team_id_fkey', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_coaches_team_id'))
        batch_op.drop_index(batch_op.f('ix_coaches_api_id'))
        batch_op.create_unique_constraint('coaches_api_id_key', ['api_id'])
        batch_op.alter_column('api_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('synced_at')

    with op.batch_alter_table('boxscores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_away', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q2_home', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q4_home', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q3_away', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q3_home', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ot_home', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q1_away', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q2_away', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q1_home', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('q4_away', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_boxscores_game_id'))
        batch_op.create_unique_constraint('boxscores_game_id_key', ['game_id'])
        batch_op.alter_column('raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('away_ot')
        batch_op.drop_column('away_q4')
        batch_op.drop_column('away_q3')
        batch_op.drop_column('away_q2')
        batch_op.drop_column('away_q1')
        batch_op.drop_column('home_ot')
        batch_op.drop_column('home_q4')
        batch_op.drop_column('home_q3')
        batch_op.drop_column('home_q2')
        batch_op.drop_column('home_q1')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.create_unique_constraint('app_settings_key_key', ['key'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
